### PR TITLE
Some fixes in fr/locale.cfg

### PR DESCRIPTION
**Pull request by sollevix67**
Fixed locale/fr/locale.cfg by removing a string that shouldn't be here,
Removed a duplicate key in fr/locale.cfg

### CODE REVIEW

**Comment by notnotmelon** [comment]
Thanks for the PR. But it seems to be a duplicate.

**Comment by Fr-Dae** [comment]
Hello, thanks your for your contribution, 
before open issue or make a PR? make sure it's not already existed.
=)

**Comment by Fr-Dae** [comment]
https://github.com/notnotmelon/maraxsis/pull/78

**Comment by sollevix67** [comment]
? ?
#78 was posted after mine !

**Pull request closed without merging**
